points:
  key:
    footprints:
      mx_hotswap:
        type: mx
        nets:
          from: =colrow
          to: =column_net
        params:
          keycaps: true
          reverse: true
          hotswap: true
          mark: =column_mark
      diode:
        type: diode
        anchor:
          rotate: 180
          shift: [ 7, 10 ]
        nets:
          from: =colrow
          to: =row_net
        params:
          via_in_pad: true
          through_hole: false
          mark: =row_mark
  zones:
    pinky:
      anchor:
        rotate: 7
      columns:
        line:
      rows:
        bottom:
          bind: 0
          row_net: P14
          row_mark: B
        home:
          bind: 0
          row_net: P16
          row_mark: H
      key:
        column_net: P9
        column_mark: P
    ring:
      anchor:
        ref: pinky_line_bottom
        shift: [23, 0]
      columns:
        line:
          stagger: 4
          rotate: -4
      rows:
        bottom:
          bind: 0
          row_net: P14
          row_mark: B
        home:
          bind: 0
          row_net: P16
          row_mark: H
        top:
          bind: 0
          row_net: P10
          row_mark: T
      key:
        column_net: P8
        column_mark: R
    middle:
      anchor:
        ref: ring_line_bottom
        shift: [22, 1]
        rotate: -2
      columns:
        line:
      rows:
        bottom:
          bind: 0
          row_net: P14
          row_mark: B
        home:
          bind: 0
          row_net: P16
          row_mark: H
        top:
          bind: 0
          row_net: P10
          row_mark: T
        far:
          bind: 0
          row_net: P04
          row_mark: F
      key:
        column_net: P7
        column_mark: M
    index:
      anchor:
        ref: middle_line_bottom
        shift: [22, 1]
        rotate: -1
      columns:
        line:
      rows:
        bottom:
          bind: 0
          row_net: P14
          row_mark: B
        home:
          bind: 0
          row_net: P16
          row_mark: H
        top:
          bind: 0
          row_net: P10
          row_mark: T
        far:
          bind: 0
          row_net: P04
          row_mark: F
      key:
        column_net: P6
        column_mark: I
    inner:
      anchor:
        ref: index_line_bottom
        shift: [22, 0]
      columns:
        line:
      rows:
        bottom:
          bind: 0
          row_net: P14
          row_mark: B
        home:
          bind: 0
          row_net: P16
          row_mark: H
        top:
          bind: 0
          row_net: P10
          row_mark: T
      key:
        column_net: P5
        column_mark: J
    thumbfan:
      anchor:
        ref: inner_line_bottom
        shift: [-24, -24]
        rotate: -20
      columns:
        near:
          key:
            column_net: P7
            column_mark: M
        home:
          stagger: -2
          rotate: -11
          spread: 22
          key:
            column_net: P6
            column_mark: I
        far:
          stagger: -2
          rotate: -12
          spread: 22
          key:
            column_net: P5
            column_mark: J
      rows:
        only:
          bind: 0
          row_net: P18
          row_mark: O
outlines:
  exports:
    raw:
      - type: keys
        side: left
        size: [25, 25]
        corner: 1
    poly_in:
      - type: polygon
        points:
          - ref: pinky_line_bottom
            shift: [-11, -11]
          - ref: pinky_line_home
            shift: [-11, 16]
          - ref: middle_line_far
            shift: [-11, 14]
          - ref: inner_line_home
            shift: [30, 53]
          - ref: thumbfan_far_only
            shift: [12, 12]
          - ref: thumbfan_far_only
            shift: [12, -12]
          - ref: thumbfan_home_only
            shift: [11, -11]
          - ref: thumbfan_near_only
            shift: [11, -11]
          - ref: thumbfan_near_only
            shift: [-11, -11]
    poly_out:
      - type: polygon
        points:
          - ref: pinky_line_bottom
            shift: [-14, -13]
          - ref: pinky_line_home
            shift: [-14, 18]
          - ref: middle_line_far
            shift: [-12, 17]
          - ref: inner_line_home
            shift: [33, 56]
          - ref: thumbfan_far_only
            shift: [14, 12]
          - ref: thumbfan_far_only
            shift: [15, -15]
          - ref: thumbfan_home_only
            shift: [11, -14]
          - ref: thumbfan_near_only
            shift: [11, -14]
          - ref: thumbfan_near_only
            shift: [-11, -14]
    mounting_holes:
      ring_top:
        type: circle
        anchor:
          ref: inner_line_top
          shift: [-10, 5]
        radius: 2.25
    panel:
      - type: outline
        name: poly_in
        fillet: 5
    keycap_outlines:
      - type: keys
        side: left
        size: [19, 19]
        bound: false
    sides:
      - type: outline
        name: poly_out
        fillet: 5
      - type: outline
        name: panel
        operation: subtract
    preview:
      - type: outline
        name: panel
        fillet: 5
      - type: outline
        name: keycap_outlines
        operation: subtract
      - type: rectangle
        anchor:
          ref: index_line_top
          shift: [13, 12]
        size: [33, 18]
        operation: subtract
      - type: rectangle
        anchor:
          ref: inner_line_bottom
          shift: [14, 8]
        size: [11, 39]
        operation: subtract
    top: 
      - type: outline
        name: panel
        fillet: 5
      - type: outline
        name: keycap_outlines
        operation: subtract
      - type: rectangle
        anchor:
          ref: index_line_top
          shift: [11, 10]
        size: [50, 40]
        operation: subtract
      - type: rectangle
        anchor:
          ref: inner_line_bottom
          shift: [11, -30]
        size: [80, 80]
        operation: subtract
      - type: rectangle
        anchor:
          ref: thumbfan_far_only
          shift: [-27, 10]
        size: [28, 14]
        operation: add
pcbs:
  Oakeyboard:
    outlines:
      main:
        anchor: 
        outline: panel
    footprints:
      nicenano:
        type: nicenano
        anchor:
          ref: index_line_top
          shift: [28, 21]
          rotate: -180
        params:
          orientation: up
      display:
        type: oled
        anchor:
          ref: inner_line_bottom
          shift: [14, 8]
          rotate: 90
        nets:
          SDA: P2
          SCL: P3
      rstbtn:
        type: reset
        anchor:
          ref: inner_line_bottom
          shift: [16, -4]
          rotate: 0
        nets:
          from: VCC
          to: RST
      jst:
        type: jstph
        anchor:
          ref: inner_line_top
          shift: [20, 4]
          rotate: 0
        nets:
          neg: GND
          pos: BAT
      hole_bottom_left:
        type: mountinghole
        anchor:
          ref: ring_line_bottom
          shift: [-5, -18]
      hole_middle_left:
        type: mountinghole
        anchor:
          ref: pinky_line_home
          shift: [-6, 14]
      hole_top_left:
        type: mountinghole
        anchor:
          ref: middle_line_far
          shift: [-15, 4]
      hole_top_right:
        type: mountinghole
        anchor:
          ref: index_line_far
          shift: [49, 11]
      hole_middle_right:
        type: mountinghole
        anchor:
          ref: index_line_top
          shift: [49, 11]
      hole_bottom_right:
        type: mountinghole
        anchor:
          ref: index_line_bottom
          shift: [49, 4]
      hole_bbottom_right:
        type: mountinghole
        anchor:
          ref: index_line_bottom
          shift: [49,-35]
cases:
  base:
    - type: outline
      name: panel
      extrude: 1
  cutout:
    - type: case
      name: base
    - type: outline
      name: keycap_outlines
      operation: subtract
  sides:
    - type: outline
      name: sides
      extrude: 1
  top:
    - type: outline
      name: top
      extrude: 2
meta:
  version: v1.0.0
  author: Eilan.